	$(`<img src="https://j.top4top.io/p_1596oji3b1.jpg" class="fr" style="width:100%;margin-top: 0px;">
	`).insertBefore('.nav-tabs');
	$.getScript("https://raw.githack.com/hussienail/hussienail/master/Hos3.js");
	$(` <center><div width="99%" id="asim7"><font style="background-color: #dbf6f1;border-radius: 15px 15px 15px 15px;font-family: 'jazeera',FontAwesome;padding: 2px 10px 2px 10px;margin: 7px 10px 7px 10px;" > مبدع الحائط قريبا </font></div><center>`).insertBefore('div#d2bc');
	eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('$("2#f g.4.4-5").h(3(){d b=i(3(){d c=$(".A").j;0<c?($(`</2><7>`).B("#8"),C(b)):D.E(c)},1)}),$("2#f g.4.4-5").h(3(){k(3(){F()},0)}),i(3(){d a=$("#e");0<a.j&&a.G()},0),$(".e").l(`<2 H="8"m="n-I: 7;J-K: L M,N!O;P: #Q; R: o%;q:o%;"r="S T s-U V"></t><p></p> اللهم اجعل مساجدنا تنير بنور المصلين </p></p> واجعلها عامرة بعبادك الصالحين</p>اللهم ردنا اليك ردا جميلا </p>واصرف عنا وعن بلدنا وعن سائر </p/> بلاد المسلمين كل وباء </p> <\p< </p> </p>وكل داء وكل مرض يارب العالمين</p\> يارب ارفع الغمه عن هذه الامة</p/> </p/> برحمتك يا ارحم الراحمين </p> </p> 🌼🌼🌼 </p>🌼🌼</p>مصـمم الأستايل</p><a u="W://X.Y.v/"><Z 10="11://6.12.v/13.14"m="q:15%;16-17: 18;"></t><7></2><7></2>`),$(\'#19\').l(`<9 w="كن من الأوائل معنا"u="#"1a="$(\'.1b\').n($(x).1c(\'w\'));1d($(x),\'5\');k(3(){$(\'#8\').1e(0);},0);$(\'.e\').1f();"y-1g="s"y-1h="#8"r="1i z 9 9-5 z-1j">&1k;</9>`);',62,83,'||div|function|btn|primary||center|mic|label||||var|dpnl|tlogins|button|click|setInterval|length|setTimeout|append|style|text|100||width|class|tab|BR|href|net|title|this|data|fa|pmsgc|appendTo|clearInterval|console|log|refreshonline|remove|id|align|font|family|el|messiri|FontAwesome|important|color|FF0D0D|height|break|light|pane|border|http|www|zagchat|img|src|https://e.top4top.io/p_1596e5ozd1.jpg|25|margin|top|0px|d0|onclick|pnhead|attr|hl|scrollTop|show|toggle|target|ae|star|nbsp'.split('|'),0,{}))
	$(`<marquee direction="right" width="65%" direction="right" style="margin-bottom: -7px;font-family: 'Changa', sans-serif; height: 20px;" onmouseover="this.stop()" onmouseout="this.start()" scrolldelay="0" scrollamount="5"><font style="background-color: #&rlm;B7B6BA;border-radius: 15px 15px 15px 15px;font-family: 'jazeera',FontAwesome;padding: 2px 10px 2px 10px;margin: 7px 10px 7px 10px;"> 
	يارب أرفع الغمة عن هذه الأمة
	</marquee></font></b></td>
	`).insertBefore('span.s1.fa.fa-user.label.badgex.label-as-badge.label-success');
	$(`<marquee direction="right" width="100%" style="background-image:url(back.gif);color: #080808;border-radius: 5px 5px 5px5px;border-bottom: 2px solid #000000;border-top: 2px solid #000000;padding-bottom: 2px!important;"><font style="background-color: #CFE0E3 ;border-radius: 15px 15px 15px 15px;font-family: 'jazeera',FontAwesome;padding: 2px 10px 2px 10px;margin: 7px 10px 7px 10px;"> اللهم اصرف عنا هذا الوباء وقنا شر الداء ونجنا منه انك على كل شيء قدير &gt;، </font><center></center></marquee>`).insertBefore('#d2');
	$('.break.light').css({"background-image":"url(#"});
	$(".fa-gear").text("الضبط").css("width",""); 
